### PR TITLE
(#97) - Update Jsch implementation

### PR DESCRIPTION
**Pull request by andreoss**
Per #97

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#102](https://github.com/jcabi/jcabi-ssh/issues/102); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by davvd** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-ssh#102` is not assigned, can't get performer

**Pull request merged**
