### PR TITLE
Added passing additional ssh session options

### PR DESCRIPTION
**Pull request by adamgo**

### CODE REVIEW

**Comment by dmarkov** [comment]
@adamgo Thanks, I will find someone to review this PR soon

**Comment by dmarkov** [comment]
@original-brownbear please review this one

**Comment by original-brownbear** [comment]
@adamgo two things before we start :

1. What issue does this relate to ? :)
2. Travis is broken.

**Comment by adamgo** [comment]
Hi @original-brownbear 

Thanks for looking at this PR. I needed a way to change PreferredAuthentications property on Jsch session config but now I realize that I can just use JSch static class methods in my own code. So I will close.

**Comment by dmarkov** [comment]
@original-brownbear **16 mins** was added to your account, many thanks for your contribution (payment AP-8P472216JB4101342)! The task took 67 hours and 44 mins.. review comments (c=1) added as a bonus. +16 added to your rating, current score is: [+9222](http://www.netbout.com/b/36646?open=rating)

**Pull request closed without merging**
