### PR TITLE
Allow Host Name Password Login

### PR DESCRIPTION
**Pull request by MichaelLampe**
Changed a single line to be in line with the normal SSH class so that if
a host name is passed it gets converted to the IP Address instead of
throwing an exception.

### CODE REVIEW

**Comment by dmarkov** [comment]
@michaellampe Thanks, someone will review your pull request soon

**Comment by dmarkov** [comment]
@yegor256 the pull request is rather small, pls review it

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@MichaelLampe are you planning to finish this?

**Comment by MichaelLampe** [comment]
@yegor256 What still needs to be done to get it merged?

**Comment by yegor256** [comment]
@MichaelLampe the branch can't be merged, since it has some problems (see the log from rultor above). I can try again...

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by dmarkov** [comment]
@yegor256 Much obliged! I have added **19 mins** to your account in payment "000-889a73a6", 2471 hours and 26 mins spent; you're getting extra minutes here (c=4); +19 to your rating, your total score is [+13712](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy now pls

**Pull request merged**
