### PR TITLE
Add Javadoc badge with automatic version detection

### PR DESCRIPTION
**Pull request by valery1707**

### CODE REVIEW

**Comment by dmarkov** [comment]
@valery1707 Many thanks for the PR, let me find a reviewer for it

**Comment by dmarkov** [comment]
@yegor256 review this pls (it's a rather short pull request)

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@yegor256 thanks, paid, **16 mins** to your account, payment ID is `000-a7a4dfde`, task took 65 hours and 47 mins to complete

you're getting extra minutes here (c=1)

+16 added to your rating, at the moment it is: [+4400](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor please deploy

**Pull request merged**
